[source.crates-io]
registry = "git://github.com/rust-lang/crates.io-index.git"

[package]
name = "aoc_2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grid = {path = "./grid" }
